Repository aws-samples/dbt-glue, pull requests merged in 2024-09, with the labels that each got.

#422 Strip unwanted partition columns
  CHANGELOG.md
  dbt/adapters/glue/impl.py
Labels: enable-functional-tests, beginning-contributor

#434 Fix unraised DbtDatabaseError
  CHANGELOG.md
  dbt/adapters/glue/gluedbapi/cursor.py
Labels: enable-functional-tests, repeat-contributor

#440 fix: add correct import for exceptions
  CHANGELOG.md
  dbt/adapters/glue/gluedbapi/connection.py
Labels: enable-functional-tests, repeat-contributor

#416 Adding minimal write option when creating table with Delta format
  CHANGELOG.md
  dbt/adapters/glue/impl.py
  dbt/include/glue/macros/materializations/incremental/incremental.sql
Labels: enable-functional-tests, beginning-contributor

#437 Fix null values handling in seeds
  CHANGELOG.md
  dbt/adapters/glue/impl.py
Labels: enable-functional-tests, beginning-contributor

#436 Fix the case-sensitive comparison on the seed name
  CHANGELOG.md
  dbt/adapters/glue/impl.py
Labels: enable-functional-tests, beginning-contributor

#448 Preparing for Release v1.8.6
  CHANGELOG.md
Labels: admired-contributor
