Repository aws-samples/dbt-glue, pull requests merged in 2025-02, with the labels that each got.

#496 Allow session isolation for some of the models
  CHANGELOG.md
  README.md
  dbt/adapters/glue/connections.py
  dbt/adapters/glue/gluedbapi/connection.py
  tests/functional/adapter/test_basic.py
Labels: enable-functional-tests, beginning-contributor

#506 Set correct session state when encountering EntityNotFound
  CHANGELOG.md
  dbt/adapters/glue/gluedbapi/connection.py
Labels: enable-functional-tests, beginning-contributor

#517 fix list_relations_without_caching for missing database
  CHANGELOG.md
  dbt/adapters/glue/impl.py
  tests/unit/test_adapter.py
Labels: beginning-contributor

#518 Fix the get_columns_in_relation function error when on_schema_change is specified
  CHANGELOG.md
  dbt/adapters/glue/impl.py
Labels: enable-functional-tests, star-contributor

#459 Allow seed type casting
  CHANGELOG.md
  README.md
  dbt/adapters/glue/credentials.py
  dbt/adapters/glue/impl.py
  tests/unit/test_adapter.py
Labels: enable-functional-tests, beginning-contributor

#514 fix 'botocore' not is not defined and add test on GlueConnection.state
  dbt/adapters/glue/gluedbapi/connection.py
  tests/unit/gluedbapi/test_connection.py
Labels: enable-functional-tests, beginning-contributor

#519 Preparing for Release v1.9.2
  CHANGELOG.md
  dbt/adapters/glue/__version__.py
  dbt/adapters/glue/impl.py
  dev-requirements.txt
  setup.py
Labels: enable-functional-tests

#520 Fixed error handling and logging
  CHANGELOG.md
  dbt/adapters/glue/impl.py
Labels: enable-functional-tests, star-contributor
